{"name": "Проверка неуспешного входа пользователя", "status": "passed", "description": "Тест проверяет неуспешный вход пользователя с неправильными данными.", "start": 1732589278113, "stop": 1732589278432, "uuid": "615b7bed-8c86-4a07-b12a-1a7f7c6e7e3e", "historyId": "aba75def0a696eeb6e8864a0fd7eb196", "testCaseId": "aba75def0a696eeb6e8864a0fd7eb196", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "192.168.1.40"}, {"name": "thread", "value": "19334-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}